[package]
name = "print"
version = "0.1.0"
authors = ["MashPlant <740678788@qq.com>"]
edition = "2018"

[dependencies]
syntax = { path = "../syntax" }
common = { path = "../common" }
tac = { path = "../tac" }
tacopt = { path = "../tacopt" }
codegen = { path = "../codegen" }